# Generated by Django 5.2.3 on 2025-09-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0007_alter_author_locale_alter_author_translation_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkpage',
            name='position',
            field=models.IntegerField(default=100, help_text='Position in the list'),
        ),
    ]
