# Generated by Django 5.2.3 on 2025-06-22 14:34

from django.db import migrations
from wagtail.models import BootstrapTranslatableModel


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0004_staff_locale_staff_translation_key"),
    ]

    operations = [
        BootstrapTranslatableModel("staff.Staff"),
    ]
