# Generated by Django 5.2.3 on 2025-06-22 14:34

from django.db import migrations
from wagtail.models import BootstrapTranslatableModel


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0003_room_locale_room_translation_key"),
    ]

    operations = [
        BootstrapTranslatableModel("schedule.Room"),
    ]
