# Generated by Django 6.0.6 on 2026-07-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_articlepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedlink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
